"""add characters

Revision ID: 227403ad98ec
Revises: 
Create Date: 2023-04-17 20:08:40.052432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227403ad98ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('portrayed_by', sa.String(length=120), nullable=True),
    sa.Column('home_town', sa.String(length=120), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('occupation', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
